TOOLS = ../tools

DL_OVERWRITE = $(TOOLS)/dl/dl-dir-log-overwrite

default:

ALL += new-funk
new-funk: force
	$(DL_OVERWRITE) $@ https://www.youtube.com/playlist?list=PL3gQ6-WYh7kV7xbBX8zI6FX2ezqJbLGE3

ALL += code
code: force
	$(DL_OVERWRITE) $@ https://www.youtube.com/playlist?list=PL3gQ6-WYh7kU-8mBvM9LHiEL0Ww39hZBW

all: $(ALL)

force:
