TOOLS = ../tools

DL_OVERWRITE = $(TOOLS)/dl/dl-dir-log-overwrite

default:

ALL += val
val: force
	$(DL_OVERWRITE) $@ https://www.youtube.com/playlist?list=PL3gQ6-WYh7kUu7bZVH8bnOdrt8Yh0G_ry

all: $(ALL)

force:
