TOOLS = ../tools

DL_OVERWRITE = $(TOOLS)/dl/dl-dir-log-overwrite

default:

ALL += val
val: force
	$(DL_OVERWRITE) $@ https://www.youtube.com/playlist?list=PL3gQ6-WYh7kV7-KC91Smicu2HXbn1Nyfy

all: $(ALL)

force:
