#!/bin/sh -e
#
# The first argument is the script to execute, relative to the tools
# directory. The second argument is the directory to download in. All other
# arguments will be proxied.
#
# If the target directory doesn't exist, it will be created.
#

readonly PROGDIR=$(dirname "$0")

script="$1"; shift
dir="$1"; shift

# Get absolute path
script=$(readlink -f "$PROGDIR/$script")

if [ ! -d "$dir" ]; then
    mkdir "$dir"
    "$PROGDIR/../mpdignore" "$dir"
fi

cd "$dir"

"$script" "$@"
