#!/usr/bin/env python3
#
# Create a relative `.mpdignore` link in given directory pointing to
# the main ignore file.
#
#     tools/mpdignore somedir
#     ls -la somedir/.mpdignore # Should be a link to `../.mpdignore`
#

import errno
import os
import sys

path = os.path.dirname(sys.argv[0]) + '/../.mpdignore'
start = sys.argv[-1]

src = os.path.relpath(path, start)
dst = start + '/.mpdignore'

try:
    os.symlink(src, dst)
except OSError as e:
    if e.errno != errno.EEXIST:
        raise e

    if not '-f' in sys.argv:
        raise e

    # Force
    os.remove(dst)
    os.symlink(src, dst)
