#!/usr/bin/awk -f

/<!-- BEGIN TASKS -->/ {
    print
    print "| Task | Description |"
    print "| ---- | ----------- |"
    system("make | sed 's/^/| /;s/:/ | /;s/$/ |/'")
    silent=1
}

/<!-- END TASKS -->/ {
    silent=0
}

!silent
