#!/usr/bin/env python3
#
# Filter a MPD database file in `stdin` to add a `Title` key for each
# music, found in a `.info.json` associated file.
#
# Since the file is found from the MPD database, the CWD should be at
# the same level as the root MPD directory.
#
#     cat ~/.config/mpd/database | codejam/tools/filter > codejam/database
#     less codejam/database # Check if everything is okay
#     cp codejam/database ~/.config/mpd/database
#

import io
import json
import os
import sys

from functools import partial
from operator import methodcaller


def info(name):
    name = '{0}.info.json'.format(os.path.splitext(name)[0])

    if not os.path.isfile(name):
        return

    with open(name, 'r') as file:
        return json.load(file)['title']


def istrip(iterable):
    return map(methodcaller('strip'), iterable)


def deflist(n, x):
    return x + [None] * (n - len(x))


def main():
    dir = '.'
    base = None

    stdin = io.TextIOWrapper(sys.stdin.buffer, encoding='utf_8')
    stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf_8')

    for line in [x.strip() for x in stdin]:
        name, value = deflist(2, line.split(': ', 1))

        if name == 'begin':
            dir = value
        elif name == 'song_begin':
            base = value
        elif name == 'Title':
            continue
        elif name == 'song_end':
            file = '/'.join([dir, base])
            title = info(file)

            if title is not None:
                stdout.write('Title: ' + title + '\n')

        stdout.write(line + '\n')


if __name__ == '__main__':
    main()
