TOOLS = ../tools

DL_OVERWRITE = $(TOOLS)/dl/dl-dir-log-overwrite

default:

ALL += sophiste-funk
sophiste-funk: force
	$(DL_OVERWRITE) $@ https://www.youtube.com/channel/UCiN8LmhebP_HIQ7g30ITdHA

ALL += val
val: force
	$(DL_OVERWRITE) $@ https://www.youtube.com/playlist?list=PL3gQ6-WYh7kX5P-SzVW5k76CDSNdfP-QV

all: $(ALL)

force:
