TOOLS = ../tools

DL_APPEND = $(TOOLS)/dl/dl-dir-log-append
DL_OVERWRITE = $(TOOLS)/dl/dl-dir-log-overwrite

default:

ALL += brown-priders-old-school-funk
brown-priders-old-school-funk: force
	$(DL_OVERWRITE) $@ https://www.youtube.com/user/BrownPriderFunk2/videos

ALL += kelly-funk
kelly-funk: force
	$(DL_OVERWRITE) $@ https://www.youtube.com/channel/UCtuzWbaytvVQivVPRjPEZuA

ALL += phillip-richardson
phillip-richardson: force
	$(DL_OVERWRITE) $@ https://www.youtube.com/channel/UCJfRo-HXZ2de-0twzl2qOLw

ALL += club-tabuvienna
club-tabuvienna: force
	$(DL_OVERWRITE) $@ https://www.youtube.com/channel/UC7kyhaeEnLmOelQZoqyOzLg

ALL += dertaube-dj
dertaube-dj: force
	$(DL_OVERWRITE) $@ https://www.youtube.com/channel/UCOKKtAy-AmXUX-xzmOvnegA

ALL += dennis-fiene
dennis-fiene: force
	$(DL_OVERWRITE) $@ https://www.youtube.com/channel/UCquqsHJqizkgGnilv_I0AQg

ALL += funk-nation
funk-nation: force
	$(DL_OVERWRITE) $@ https://www.youtube.com/channel/UCIslxYW_aALyKiCr5ZnqHnw

ALL += funk-rare
funk-rare: force
	$(DL_OVERWRITE) $@ https://www.youtube.com/channel/UCw5rm-sfzDLvnlOJHTBhakA

ALL += funky-sounds
funky-sounds: force
	$(DL_OVERWRITE) $@ https://www.youtube.com/channel/UChwYdiKilsRqJTRklKysoNQ

ALL += kool-master-style
kool-master-style: force
	$(DL_OVERWRITE) $@ https://www.youtube.com/channel/UC_ohVXXnSJNTfia5zOomaJA

ALL += way-back
way-back: force
	$(DL_OVERWRITE) $@ https://www.youtube.com/channel/UCIrC0UFDLZ93zPmkMXKCrsQ

ALL += old-school-chibani
old-school-chibani: force
	$(DL_OVERWRITE) $@ https://www.youtube.com/channel/UCO5fBZ4OwuAcz8G5hk4IOXQ

ALL += pierre-richard
pierre-richard: force
	$(DL_OVERWRITE) $@ https://www.youtube.com/channel/UCVBZ9XZcgv0h3dscFWaHNgA

ALL += slayd
slayd: force
	$(DL_OVERWRITE) $@ https://www.youtube.com/channel/UCJMDrNiBx-wOF_d3NdFu_FQ

ALL += rg-nero
rg-nero: force
	$(DL_OVERWRITE) $@ https://www.youtube.com/channel/UCg-9BSiMMszdo95_fKqL95g

ALL += old-school-music
old-school-music: force
	$(DL_OVERWRITE) $@ https://www.youtube.com/user/TheOldSchoolMusic

ALL += tmontyb
tmontyb: force
	$(DL_OVERWRITE) $@ https://www.youtube.com/user/tmontyb100012

ALL += unidisc-music-disco
unidisc-music-disco: force
	$(DL_OVERWRITE) $@ https://www.youtube.com/playlist?list=PLFC4BA32446E8A8DA

ALL += unidisc-music-funk
unidisc-music-funk: force
	$(DL_OVERWRITE) $@ https://www.youtube.com/playlist?list=PL895AF381DA6E83E0

ALL += infinity-fmde
infinity-fmde: force
	$(DL_OVERWRITE) $@ https://www.youtube.com/channel/UCyAVUYIUJFAnHKZopZIXjeg

ALL += luiz-eduardo-carvalho
luiz-eduardo-carvalho: force
	$(DL_OVERWRITE) $@ https://www.youtube.com/channel/UCCPkuuKXKGwUNpMpkXRYAAw

ALL += cool-funk-zeze
cool-funk-zeze: force
	$(DL_OVERWRITE) $@ https://www.youtube.com/channel/UC5TdsDGZ7-nja9nJb8vtZIQ

ALL += tom-disco-club
tom-disco-club: force
	$(DL_OVERWRITE) $@ https://www.youtube.com/channel/UC8Vnz_8DW_PEDqzthv6pcKQ

ALL += val
val: force
		$(DL_OVERWRITE) $@ https://www.youtube.com/playlist?list=PL3gQ6-WYh7kXDgU5mfzJ4aUVPdtgCCdD1; \
		$(DL_APPEND) $@ https://www.youtube.com/playlist?list=PL3gQ6-WYh7kVHwNcppS5Lb0tgz0qzYGg5; \
		$(DL_APPEND) $@ https://www.youtube.com/playlist?list=PL3gQ6-WYh7kV3KIIGPcSvjd6E7JemZPMb; \
		$(DL_APPEND) $@ https://www.youtube.com/playlist?list=PL3gQ6-WYh7kX4hHvmPkF4xHbCpMP3zwEm; \
		$(DL_APPEND) $@ https://www.youtube.com/playlist?list=PL3gQ6-WYh7kU1HF0Fwc4eG3nRg11063Xy

all: $(ALL)

force:
